version: '3.8'

services:

  redis:
    image: redis:8.2
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:18.0
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  worker:
    image: dockersamples/examplevotingapp_worker
    container_name: worker
    depends_on:
      - db
      - redis

  voting_app:
    image: dockersamples/examplevotingapp_vote
    container_name: voting_app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    ports:
      - "8001:80"

  result_app:
    image: dockersamples/examplevotingapp_result
    container_name: result_app
    depends_on:
      - db
    ports:
      - "8002:80"
