apiVersion: v1
kind: Service
metadata:
  name: result-app
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
  labels:
    app: result-app-svc
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 80
  selector:
    app: result-app
